### ISSUE TITLE
Error using LibSass complier

### ISSUE THREAD

**Issue by Clarimmy** [AlphaAlec/gymnast#1]
Using LibSass to compile and I'm getting the error:
`error parsing interpolated value`

Might be related to: https://github.com/sass/libsass/issues/1277

**Comment by AlphaAlec** [comment]
Ah yes, SCSS updated how they do interpolation. I'll get on it asap, thanks for the notification!

**Comment by AlphaAlec** [comment]
Having trouble replicating the issue; do you know which line is causing the error?

**Comment by Clarimmy** [comment]
I think line 166

`166    error parsing interpolated value    // -------------------------------`

**Comment by AlphaAlec** [comment]
Apologies for the delay. I just updated how the nth-of-type(n+1) rules work, and my hope is that will fix the issue. Can you pull and please confirm?

**Comment by Clarimmy** [comment]
No worries! 

But yeah, it did fix it. It complied no problem.

Thanks!

**Comment by AlphaAlec** [comment]
No, thank you!
